version: 2

models:
  - name: mart_loss_ratio
    description: "Ratio S/P (Loss Ratio) par branche, région et année de survenance"
    columns:
      - name: line_of_business
        tests:
          - not_null
      - name: accident_year
        tests:
          - not_null
      - name: earned_premium_eur
        tests:
          - not_null

  - name: mart_claims_frequency
    description: "Analyse de la fréquence et de la sévérité des sinistres par segment"
    columns:
      - name: line_of_business
        tests:
          - not_null
      - name: accident_year
        tests:
          - not_null

  - name: mart_portfolio_performance
    description: "Concentration et performance du portefeuille avec réassurance"
    columns:
      - name: line_of_business
        tests:
          - not_null
      - name: total_premium_eur
        tests:
          - not_null
